home_app/urls.py
from django.urls import path

from home_app import views

app_name = 'home'
urlpatterns = [
    path('', views.index),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.gallery, name='gallery'),
    path('index/', views.index, name='index'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls'))
]

home_app/models.py
from django.db import models
from django.utils.timezone import now


class gallery(models.Model):
    date = models.DateTimeField(auto_now=True, auto_created=True)
    name = models.CharField(max_length=25, verbose_name="Image Name")
    picture = models.FileField(upload_to="gallery")

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'GALLERY'
        verbose_name_plural = 'GALLERY'


class passed_weddings(models.Model):
    date = models.DateTimeField(auto_now=True, auto_created=True)
    name = models.CharField(max_length=25, verbose_name="Image Name")
    bride = models.CharField(max_length=25, verbose_name="Bride's Name")
    groom = models.CharField(max_length=25, verbose_name="Groom's Name")
    picture = models.FileField(upload_to="gallery")

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'PASSED WEDDING'
        verbose_name_plural = 'PASSED WEDDINGS'

home_app/views.py
from django.shortcuts import render


def about(request):
    template_name = 'about.html'
    return render(request, template_name)


def contact(request):
    template_name = 'contact.html'
    return render(request, template_name)


def gallery(request):
    template_name = 'gallery.html'
    return render(request, template_name)


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="eng">
<head>
    <title>BBI | About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="BBI Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design"/>
    <script type="application/x-javascript">
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- // Meta Tags -->
    <!--booststrap-->
    <link href=" {% static 'css/bootstrap.min.css' %} " rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <!-- font-awesome icons -->
    <link href=" {% static 'css/fontawesome-all.css' %} " rel="stylesheet">
    <!-- //font-awesome icons -->
    <!--stylesheets-->
    <link href=" {% static 'css/style.css' %} " rel='stylesheet' type='text/css' media="all">
    <!--//stylesheets-->
    <link href=" {% static '//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i' %} "
          rel="stylesheet">
    <link href=" {% static '//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700' %} "
          rel="stylesheet">
</head>
<body>

<!--/banner-->
<!-- banner -->
{% include 'includes/menu_headers.html' %}
<!-- //banner -->
<section class="banner_bottom py-5">
    <div class="container py-md-4 mt-md-3">
        <div class="wthree_head_section">
            <h2 class="w3l_header">About <span>Us</span></h2>
        </div>
        <div class="inner_sec_info_wthree_agile mt-md-5 pt-4">
            <div class="row help_full">
                <div class="col-lg-6 banner_bottom_grid help">
                    <img src=" {% static 'images/g6.jpg' %} " alt=" " class="img-fluid">
                </div>
                <div class="col-lg-6 banner_bottom_left">
                    <h4>Lorem Ipsum convallis diam</h4>
                    <p>Pellentesque convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla
                        viverra pharetra sem, eget
                        pulvinar neque pharetra ac.</p>
                    <p>Lorem Ipsum convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra
                        pharetra sem, eget
                        pulvinar neque pharetra ac.</p>
                    <p>Lorem Ipsum convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra
                        pharetra sem, eget
                        pulvinar neque pharetra ac.</p>
                    <p>Lorem Ipsum convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra
                        pharetra sem, eget
                        pulvinar neque pharetra ac.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--//ab-->
<!-- stats -->
<section class="stats">
    <div class="overlay py-5">
        <div class="container py-md-4 mt-md-3">
            <div class="wthree_head_section">
                <h3 class="w3l_header text-white">Our <span class="text-white">Credits</span></h3>
            </div>
            <div class="row inner_w3l_agile_grids-1 mt-md-5 pt-4">
                <div class="col-md-4 w3layouts_stats_left w3_counter_grid">
                    <i class="fas fa-image" aria-hidden="true"></i>
                    <p>120</p>
                    <h3>PHOTOGRAPHERS</h3>
                </div>
                <div class="col-md-4 w3layouts_stats_left w3_counter_grid1">
                    <i class="fas fa-smile" aria-hidden="true"></i>
                    <p>150</p>
                    <h3>TYPES OF FLOWERS</h3>
                </div>
                <div class="col-md-4 w3layouts_stats_left w3_counter_grid3">
                    <i class="fas fa-car" aria-hidden="true"></i>
                    <p>60</p>
                    <h3>WEDDING CARS</h3>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- //stats -->
<!-- team -->
<section class="wthree-row py-5">
    <div class="container py-md-4 mt-md-3">
        <div class="wthree_head_section">
            <h3 class="w3l_header">Our <span>BBIraphers</span></h3>
        </div>
        <div class="row mt-md-5 pt-4">
            <div class="col-lg-3 col-sm-6 team-grids">
                <div class="team-effect">
                    <img src=" {% static 'images/te1.jpg' %} " alt="img" class="img-fluid">
                </div>
                <!-- team text -->
                <div class="footerv2-w3ls mt-3">
                    <h4 class="mb-2">John Smith</h4>
                    <p class="mb-2">Wedding</p>
                    <ul class="social-iconsv2 agileinfo">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- //team text -->
            </div>
            <div class="col-lg-3 col-sm-6 team-grids mt-sm-0 mt-5">
                <div class="team-effect">
                    <img src=" {% static 'images/te3.jpg' %} " alt="img" class="img-fluid">
                </div>
                <!-- team text -->
                <div class="footerv2-w3ls mt-3">
                    <h4 class="mb-2">Thomson Doe</h4>
                    <p class="mb-2">Classic</p>
                    <ul class="social-iconsv2 agileinfo">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- //team text -->
            </div>
            <div class="col-lg-3 col-sm-6 team-grids mt-lg-0 mt-5">
                <div class="team-effect">
                    <img src=" {% static 'images/te2.jpg' %} " alt="img" class="img-fluid">
                </div>
                <!-- team text -->
                <div class="footerv2-w3ls mt-3">
                    <h4 class="mb-2">Smith Kevin</h4>
                    <p class="mb-2">Creative</p>
                    <ul class="social-iconsv2 agileinfo">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- //team text -->
            </div>
            <div class="col-lg-3 col-sm-6 team-grids mt-lg-0 mt-5">
                <div class="team-effect">
                    <img src=" {% static 'images/te4.jpg' %} " alt="img" class="img-fluid">
                </div>
                <!-- team text -->
                <div class="footerv2-w3ls mt-3">
                    <h4 class="mb-2">Laura Hill</h4>
                    <p class="mb-2">Birthdays</p>
                    <ul class="social-iconsv2 agileinfo">
                        <li>
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- //team text -->
            </div>
        </div>
    </div>
</section>
<!-- //team -->
<!-- //footer -->
{% include 'includes/footer.html' %}

templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="eng">
<head>
    <title>BBI | Contact</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="BBI Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design"/>
    <script type="application/x-javascript">
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- // Meta Tags -->
    <!--booststrap-->
    <link href=" {% static 'css/bootstrap.min.css' %} " rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <!-- font-awesome icons -->
    <link href=" {% static 'css/fontawesome-all.css' %} " rel="stylesheet">
    <!-- //font-awesome icons -->
    <!--stylesheets-->
    <link href=" {% static 'css/style.css' %} " rel='stylesheet' type='text/css' media="all">
    <!--//stylesheets-->
    <link href=" {% static '//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i' %} "
          rel="stylesheet">
    <link href=" {% static '//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700' %} "
          rel="stylesheet">
</head>
<body>

<!--/banner-->
<!-- banner -->
{% include 'includes/menu_headers.html' %}
<!-- //banner -->
<!-- contact -->
<section class="contact-innpage py-5">
    <div class="container py-md-4 mt-md-3">
        <div class="wthree_head_section">
            <h2 class="w3l_header">Get in <span>Touch</span></h2>
        </div>
        <form action="#" method="post">
            <div class="row mail_grid_w3l mt-md-5 pt-4">

                <div class="col-md-6 contact_left_grid">
                    <div class="contact-fields-w3ls">
                        <input type="text" name="Name" placeholder="Name" required="">
                    </div>
                    <div class="contact-fields-w3ls">
                        <input type="email" name="Email" placeholder="Email" required="">
                    </div>
                    <div class="contact-fields-w3ls">
                        <input type="text" name="Telephone" placeholder="Telephone" required="">
                    </div>
                    <div class="contact-fields-w3ls">
                        <input type="text" name="Subject" placeholder="Subject" required="">
                    </div>
                </div>
                <div class="col-md-6 contact_left_grid rgt_gd">
                    <div class="contact-fields-w3ls">
                        <textarea name="Message" placeholder="Message..." required=""></textarea>
                    </div>
                    <input type="submit" value="Submit">
                </div>
            </div>
        </form>
    </div>
</section>
<!-- //contact -->
<section class="map-section">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387193.30591910525!2d-74.25986432970718!3d40.697149422113014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew+York%2C+NY%2C+USA!5e0!3m2!1sen!2sin!4v1521710297542"></iframe>
</section>
<!-- //footer -->
{% include 'includes/footer.html' %}

templates/gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="eng">
<head>
    <title>BBI | Gallery</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="BBI Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design"/>
    <script type="application/x-javascript">
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- // Meta Tags -->
    <!--booststrap-->
    <link href=" {% static 'css/bootstrap.min.css' %} " rel="stylesheet" type="text/css" media="all">
    <!--//booststrap end-->
    <link rel="stylesheet" href=" {% static 'css/chocolat.css' %} " type="text/css" media="screen">
    <!-- //Gallery Css -->
    <!-- font-awesome icons -->
    <link href=" {% static 'css/fontawesome-all.css' %} " rel="stylesheet">
    <!-- //font-awesome icons -->
    <!--stylesheets-->
    <link href=" {% static 'css/style.css' %} " rel='stylesheet' type='text/css' media="all">
    <!--//stylesheets-->
    <link href=" {% static '//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i' %} "
          rel="stylesheet">
    <link href=" {% static '//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700' %} "
          rel="stylesheet">
</head>
<body>

<!--/banner-->
<!-- banner -->
{% include 'includes/menu_headers.html' %}
<!-- //banner -->
<!--Gallery-->
<section class="gallery py-5">
    <div class="container py-md-4 mt-md-3">
        <div class="wthree_head_section">
            <h2 class="w3l_header">Gallery </h2>
        </div>
        <div class="row agile_gallery_grids w3-agile demo mt-md-5 pt-4">
            <div class="col-md-4 gal-sec">
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g1.jpg' %} ">
                        <img src=" {% static 'images/g1.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g2.jpg' %} ">
                        <img src=" {% static 'images/g2.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g3.jpg' %} ">
                        <img src=" {% static 'images/g3.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 gal-sec">
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g4.jpg' %} ">
                        <img src=" {% static 'images/g4.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana" href=" {% static 'images/g5.jpg' %} ">
                        <img src=" {% static 'images/g5.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g6.jpg' %} ">
                        <img src=" {% static 'images/g6.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4 gal-sec">
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g7.jpg' %} ">
                        <img src=" {% static 'images/g7.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g8.jpg' %} ">
                        <img src=" {% static 'images/g8.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
                <div class="gallery-grid1">
                    <a title="Nulla porttitor accumsana." href=" {% static 'images/g9.jpg' %} ">
                        <img src=" {% static 'images/g9.jpg' %} " alt=" " class="img-responsive"/>
                        <div class="p-mask">
                            <h4>BBI</h4>
                            <p>Gallery</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--//Gallery-->
<!-- //footer -->
{% include 'includes/footer.html' %}

templates/includes/footer.html
{% load static %}
<footer>
    <section class="footer footer_w3layouts_section_1its py-5">
        <div class="container py-md-4">
            <div class="row footer-top">
                <div class="col-lg-3 col-md-6 col-sm-6 footer-grid_section_1its_w3">
                    <div class="footer-title">
                        <h3>About Us</h3>
                    </div>
                    <div class="footer-text">
                        <p>Curabitur non nulla sit amet nislinit tempus convallis quis ac lectus. lac inia eget
                            consectetur sed, convallis at tellus.
                            Nulla porttitor accumsana tincidunt. Vestibulum ante ipsum primis tempus convallis.</p>
                        <ul class="social_section_1info">
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fab fa-google-plus-g"></i></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin-in"></i></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 footer-grid_section_1its_w3">
                    <div class="footer-title">
                        <h3>Contact Info</h3>
                    </div>
                    <div class="contact-info">
                        <h4>Location :</h4>
                        <p>5B Twin Palm Road, Kabulonga, Lusaka, Zambia.</p>
                        <div class="phone">
                            <h4>Phone :</h4>
                            <p>Phone : +260 964 649520</p>
                            <p>Email : <a href="mailto:efficient.tech.zm@gmail.com">info@bbievents.com</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 footer-grid_section_1its_w3">
                    <div class="footer-title">
                        <h3>Useful Links</h3>
                    </div>
                    <ul class="links">
                        <li><a href=" {% url 'home:index' %} ">Home</a></li>
                        <li><a href=" {% url 'home:about' %} ">About</a></li>
                        <li><a href=" {% url 'home:gallery' %} ">Gallery</a></li>
                        <li><a href=" {% url 'home:contact' %} ">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 footer-grid_section_1its_w3">
                    <div class="footer-title">
                        <h3>Subscribe</h3>
                    </div>
                    <div class="footer-text">
                        <p>By subscribing to our mailing list you will always get latest news and updates from us.</p>
                        <form action="#" method="post">
                            <input type="email" name="Email" placeholder="Enter your email..." required="">
                            <button class="btn1"><i class="fa fa-envelope" aria-hidden="true"></i></button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="copyright pt-4 mt-4">
                <p>© 2022 BBI. All Rights Reserved | Design By <a href="mailto:efficient.tech.zm@gmail.com">Efficient
                    Technologies</a></p>
            </div>
        </div>
    </section>
</footer>
<!-- //footer -->
<!--js working-->
<script src=" {% static 'js/jquery.min.js' %} "></script>
<!--//js working-->
<!-- smooth scrolling -->
<script type="text/javascript" src=" {% static 'js/move-top.js' %} "></script>
<script type="text/javascript" src=" {% static 'js/easing.js' %} "></script>
<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function () {
        /*
            var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
            };
        */
        $().UItoTop({easingType: 'easeOutQuart'});

    });
</script>
<!-- //here ends scrolling icon -->
<!-- //smooth scrolling -->
<!-- typer js-->
<!-- For banner text -->
<script src=' {% static 'js/jquery.typer.js' %} '></script>
<script>
    var win = $(window),
        foo = $('#typer');
    foo.typer(['AT BBI EVENTS, WE CREATE YOUR SPECIAL DAY', 'AT BBI EVENTS, WE CREATE YOUR SPECIAL DAY', 'AT BBI EVENTS, WE CREATE YOUR SPECIAL DAY']);
    // unneeded...
    win.resize(function () {
        var fontSize = Math.max(Math.min(win.width() / (1 * 10), parseFloat(Number.POSITIVE_INFINITY)), parseFloat(Number.NEGATIVE_INFINITY));
        foo.css({
            fontSize: fontSize * .8 + 'px'
        });
    }).resize();
</script>
<!-- //typer js-->
<!-- //For banner text -->
<!-- scrolling script -->
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);
        });
    });
</script>
<!-- //scrolling script -->
<script src=" {% static 'js/main.js' %} "></script>
<!-- Calendar -->
<script src=" {% static 'js/jquery-ui.js' %} "></script>
<script>
    $(function () {
        $("#datepicker,#datepicker1,#datepicker2,#datepicker3").datepicker();
    });
</script>
<!-- //Calendar -->
<!--bootstrap working-->
<script src=" {% static 'js/bootstrap.min.js' %} "></script>
<!-- //bootstrap working-->
</body>
</html>

templates/includes/menu_headers.html
{% load static %}
<header>
    <section class="main_section_agile">
        <div class="agileits_w3layouts_banner_nav">
            <div class="header-bar py-sm-2">
                <div class="container py-2">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <div class="hedder-up">
                            <h1><a class="navbar-brand" href=" {% url 'home:index' %} ">BBI</a></h1>
                        </div>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item active">
                                    <a class="nav-link" href="  {% url 'home:index' %} ">Home <span
                                            class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a href="  {% url 'home:about' %} " class="nav-link">About</a>
                                </li>
                                <li class="nav-item">
                                    <a href="  {% url 'home:gallery' %} " class="nav-link ">Gallery</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                       data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">
                                        Pages
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href=" {% url 'home:index' %} ">Codes</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href=" {% url 'home:index' %} ">About</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a href=" {% url 'home:contact' %}" class="nav-link">Contact</a>
                                </li>
                            </ul>
                            <div class="w3_agile_login">
                                <div class="cd-main-header">
                                    <a class="cd-search-trigger" href=" {% static '#cd-search' %} "> <span></span></a>
                                    <!-- cd-header-buttons -->
                                </div>
                                <div id="cd-search" class="cd-search">
                                    <form action="#" method="post">
                                        <input name="Search" type="search" placeholder="Search...">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
            <!-- //Navigation -->
        </div>
        <!-- w3-banner -->
        <div class="w3-banner">
            <div id="typer"></div>
            <p class="mx-auto py-3">Praesent sit amet fermentum ipsum. Cras dictum ante nec metus pretium, placerat
                hendrerit ex facilisis.
                Ut sed neque sem. Ut ipsum dolor, dapibus et imperdiet nec, ultricies non metus.</p>
        </div>
        <!-- //w3-banner -->
    </section>
</header>